kind: Service
apiVersion: v1
metadata:
  name: usermanager-service
spec:
  type: NodePort
  selector:
    app: usermanager-api
  ports:
    - nodePort: 30001
      port: 30001
      targetPort: 30001
---
apiVersion: v1
kind: Pod
metadata:
  name: usermanager
  labels:
    app: usermanager-api
spec:
  containers:
    - name: sample-api
      image: rmkanda/sample-api-service:latest
      resources:
        requests:
          memory: "512Mi"
          cpu: "1000m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - "ALL"
          add: ["NET_ADMIN", "SYS_TIME"]